name: Latest Image

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build -t ghcr.io/ynuosa/mirrors-webui:latest .
    - name: Push docker image to ghcr.io
      run: docker push ghcr.io/ynuosa/mirrors-webui:latest
